export const titles: Record<string, [string, string]> = {
  console:['Platform Console','yoMall SaaS · every mall on the network'],
  lending:['Lending Partner Console','Loan applications, KYC review & disbursement'],
  landlords:['Landlords','Landlord accounts, verification and payout details'],
  performance:['Mall Performance','Operational SLA metrics across every mall'],
  moderation:['Deal Moderation','Review deals before they go live on yoDeals'],
  escalations:['Escalations','Disputes escalated from tenant-landlord messaging'],
  broadcast:['Broadcast','Send a platform-wide notice to landlords or tenants'],
  privacy:['Privacy & Data','Manage stored KYC data — export or delete on request'],
  audit:['Audit Log','Every administrative action taken on the platform'],
  overview:['Overview','Key metrics across your building'],
  floormap:['Floor & Unit Map','48 units across 3 floors'],
  tenants:['Tenant Directory','Manage leases, contacts and storefront status'],
  storefront:['Storefront','Shop profile on the mall guide app'],
  yodeals:['Post to yoDeals','Special offers and discounts — not a full product catalogue'],
  guide:['Mall Guide Content','Wayfinding, amenities and customer announcements'],
  rent:['Rent & Payments','Landlord advances and tenant repayment plans'],
  deliveries:['Deliveries & yoDeals Sales','Monitor online orders and rider status'],
  staff:['Maintenance & Support','Directory of on-call building staff'],
  renewals:['Lease Renewals','Upcoming lease expirations across your building'],
  reports:['Reports','Export building data for your own records'],
  team:['Team','People with access to manage this building'],
  documents:['Documents','Compliance certificates and building documents'],
  handbook:['Tenant Handbook','Building operating rules for all tenants'],
  't-overview':['My Shop','Nyabugogo TechHub · Unit G-14'],
  't-orders':['My Orders','Online orders placed through yoDeals'],
  't-rent':['My Rent','Your repayment plan and payment history'],
  't-lease':['My Lease','Your lease terms, charges, deposit and compliance'],
  't-messages':['Messages','Contact your property manager directly'],
  'pos':['MSME Biz Wizard','Sales, invoices, stock and tax for your shop'],
  'chinatown':['ChinaTown','Shared containers, sourcing requests and customs financing'],
};

export const landlordNavItems: { view: string; label: string }[] = [
  { view: 'overview', label: 'Overview' },
  { view: 'floormap', label: 'Floor & Unit Map' },
  { view: 'tenants', label: 'Tenant Directory' },
  { view: 'storefront', label: 'Storefront' },
  { view: 'yodeals', label: 'Post to yoDeals' },
  { view: 'guide', label: 'Mall Guide Content' },
  { view: 'renewals', label: 'Lease Renewals' },
  { view: 'reports', label: 'Reports' },
  { view: 'team', label: 'Team' },
  { view: 'documents', label: 'Documents' },
  { view: 'handbook', label: 'Tenant Handbook' },
  { view: 'rent', label: 'Rent & Payments' },
  { view: 'deliveries', label: 'Deliveries & yoDeals Sales' },
  { view: 'staff', label: 'Maintenance & Support' },
];
